import Head from "next/head";
import Hero from "./Hero";
import Best from "./Best";
import Featured from "./Featured";
import Footer from "./Footer";
import Navbar from "./Navbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Hero />
      <Best />
      <Featured />
      <Footer />
    </div>
  );
}
